/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.HuespedDAO;
import modelo.Huesped;
import conexion.conexionBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import modelo.TablaHuesped;

/**
 *
 * @author erik
 */
public class AgregarHuesped extends javax.swing.JFrame implements KeyListener {
    conexionBD conexion;
    JButton btn_actualizar = new JButton("Actualizar");
    TablaHuesped tb = new TablaHuesped();
    JTable mod = new JTable();
    /**
     * Creates new form AgregarHuesped
     */
    public AgregarHuesped() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public AgregarHuesped(conexionBD conexion,JTable tabla) {
        this.conexion = conexion;
        mod = tabla;
        initComponents();
        txt_nombre_hueped.addKeyListener(this);
        txt_pa_huesped.addKeyListener(this);
        txt_sa_huesped.addKeyListener(this);
        txt_email_huesped.addKeyListener(this);
        txt_telefono_huesped.addKeyListener(this);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre_hueped = new javax.swing.JTextField();
        txt_pa_huesped = new javax.swing.JTextField();
        txt_sa_huesped = new javax.swing.JTextField();
        txt_email_huesped = new javax.swing.JTextField();
        txt_telefono_huesped = new javax.swing.JTextField();
        cmb_pais_huesped = new javax.swing.JComboBox<>();
        cmb_identificacion_huesped = new javax.swing.JComboBox<>();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nombre");

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        jLabel6.setText("Email");

        jLabel7.setText("Telefono");

        jLabel9.setText("Pais");

        jLabel10.setText("Identificacion");

        txt_nombre_hueped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_huepedActionPerformed(evt);
            }
        });

        cmb_pais_huesped.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mexico", "Argentina", "Canada", " " }));

        cmb_identificacion_huesped.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false", " " }));

        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/agregar.png"))); // NOI18N
        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eliminar.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(49, 128, 205));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setText("Agregar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_identificacion_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_sa_huesped)
                                .addComponent(txt_pa_huesped)
                                .addComponent(txt_nombre_hueped)
                                .addComponent(txt_email_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_telefono_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_pais_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre_hueped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pa_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_sa_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_email_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_telefono_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmb_pais_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_identificacion_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombre_huepedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_huepedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_huepedActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        Huesped h = new Huesped();
        HuespedDAO hdao = new HuespedDAO();
        
        boolean x = false,x1= false,x2= false,x3= false,x5= false;
        
        
        if(txt_nombre_hueped.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(rootPane, "la caja nombre esta vacia");
           x = true;
           System.out.println(x);
        }
        if(txt_pa_huesped.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "la caja primer apellido esta vacia");
            x1 = true;
            System.out.println(x1);
        }
        if(txt_pa_huesped.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "la caja segundo apellido esta vacia");
            x2 = true;
            System.out.println(x2);
        }
        if(txt_email_huesped.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "la caja correo esta vacia");
            x3 = true;
            System.out.println(x3);
        }
        if(txt_telefono_huesped.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "la caja telefono esta vacia");
            x5 = true;
            System.out.println(x5);
        }
        else{
            
        }
        
        if(x && x1 && x2 && x3  && x5){
            
        }
        else{
            h.setNombreHuesped(txt_nombre_hueped.getText());
            h.setPrimerApellido(txt_pa_huesped.getText());
            h.setSegundoApellido(txt_sa_huesped.getText());
            
            h.setEmail(txt_email_huesped.getText());
            h.setTelefono(txt_telefono_huesped.getText());
            h.setPais(String.valueOf(cmb_pais_huesped.getSelectedItem()));
            h.setIdentificacion(Boolean.valueOf(String.valueOf(cmb_identificacion_huesped.getSelectedItem())));
            
            if(hdao.agregarHuesped(conexion, h)){
                
                tb.ver_tabla(mod, conexion);
                JOptionPane.showMessageDialog(rootPane, "inserccion exitosa");
                this.setDefaultCloseOperation(HIDE_ON_CLOSE);
            }
        }
        
        
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        // TODO add your handling code here:
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    public void accionActualizarRegistro(Huesped h,conexionBD co,JTable tabla){
        
        btn_aceptar.setVisible(false);
        btn_actualizar.setBounds(170, 405, 115, 28);
        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/actualizar.png")));
        btn_actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(btn_actualizar);
        
        boolean x = false,x1= false,x2= false,x3= false,x5= false;
        
        txt_nombre_hueped.setText(h.getNombreHuesped());
        txt_pa_huesped.setText(h.getPrimerApellido());
        txt_sa_huesped.setText(h.getSegundoApellido());
        txt_email_huesped.setText(h.getEmail());
        txt_telefono_huesped.setText(h.getTelefono());
        
        
        if(txt_nombre_hueped.getText().equalsIgnoreCase("")){
           JOptionPane.showMessageDialog(rootPane, "la caja nombre esta vacia");
           x = true;
           System.out.println(x);
        }
        if(txt_pa_huesped.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "la caja primer apellido esta vacia");
            x1 = true;
            System.out.println(x1);
        }
        if(txt_pa_huesped.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "la caja segundo apellido esta vacia");
            x2 = true;
            System.out.println(x2);
        }
        if(txt_email_huesped.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "la caja correo esta vacia");
            x3 = true;
            System.out.println(x3);
        }
        if(txt_telefono_huesped.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(rootPane, "la caja telefono esta vacia");
            x5 = true;
            System.out.println(x5);
        }
        else{
            
        }
        
        if(x && x1 && x2 && x3  && x5){
            
        }
        else{
        
            btn_actualizar.addActionListener(new ActionListener() {
            
            
                @Override
                public void actionPerformed(ActionEvent ae) {
                    Huesped h1 = new Huesped();
                    HuespedDAO hdao = new HuespedDAO();
                    h1.setIdHuesped(h.getIdHuesped());
                    h1.setNombreHuesped(txt_nombre_hueped.getText());
                    h1.setPrimerApellido(txt_pa_huesped.getText());
                    h1.setSegundoApellido(txt_sa_huesped.getText());
                    h1.setEmail(txt_email_huesped.getText());
                    h1.setTelefono(txt_telefono_huesped.getText());
                    h1.setPais(String.valueOf(cmb_pais_huesped.getSelectedItem()));
                    h1.setIdentificacion(Boolean.valueOf(String.valueOf(cmb_identificacion_huesped.getSelectedItem())));
                    System.out.println(co);
                    if(hdao.actualizarHuesped(co, h1)){
                        tb.ver_tabla(tabla, conexion);
                        JOptionPane.showMessageDialog(rootPane, "actualizacion exitosa");
                    }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        }
        
        
        
        //btn_actualizar.addActionListener();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarHuesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JComboBox<String> cmb_identificacion_huesped;
    private javax.swing.JComboBox<String> cmb_pais_huesped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_email_huesped;
    private javax.swing.JTextField txt_nombre_hueped;
    private javax.swing.JTextField txt_pa_huesped;
    private javax.swing.JTextField txt_sa_huesped;
    private javax.swing.JTextField txt_telefono_huesped;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent ke) {
        
        
        if(ke.getComponent().equals(txt_nombre_hueped) || ke.getComponent().equals(txt_pa_huesped) || 
                ke.getComponent().equals(txt_sa_huesped)){
            if(Character.isAlphabetic(ke.getKeyChar())){
                
            }
            else{
                ke.consume();
            }     
        }
        else if(ke.getComponent().equals(txt_telefono_huesped)){
            if(Character.isDigit(ke.getKeyChar())){
                
            }
            else{
                ke.consume();
            }
        }
        else if(ke.getComponent().equals(txt_email_huesped)){
            if(Character.isLetterOrDigit(ke.getKeyChar()) || Character.isSpaceChar(ke.getKeyChar()) || ke.getKeyChar() == '.'
                    || ke.getKeyChar() == '@'){
                
            }
            else{
                ke.consume();
            }
        }
        //ke.getComponent().equals(txt_pa_huesped)
          //      || ke.getComponent().equals(txt_sa_huesped)
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyPressed(KeyEvent ke) {
        //solo_alfabeto(txt_nombre_hueped);
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void keyReleased(KeyEvent ke) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
