/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.HuespedDAO;
import modelo.Huesped;
import conexion.conexionBD;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author erik
 */
public class AgregarHuesped extends javax.swing.JFrame {
    conexionBD conexion;
    JButton btn_actualizar = new JButton("Actualizar");
    /**
     * Creates new form AgregarHuesped
     */
    public AgregarHuesped() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public AgregarHuesped(conexionBD conexion) {
        this.conexion = conexion;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre_hueped = new javax.swing.JTextField();
        txt_pa_huesped = new javax.swing.JTextField();
        txt_sa_huesped = new javax.swing.JTextField();
        txt_direccion_hueped = new javax.swing.JTextField();
        txt_email_huesped = new javax.swing.JTextField();
        txt_telefono_huesped = new javax.swing.JTextField();
        cmb_pais_huesped = new javax.swing.JComboBox<>();
        cmb_identificacion_huesped = new javax.swing.JComboBox<>();
        btn_aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jLabel1.setText("Agregar");

        jLabel2.setText("Nombre");

        jLabel3.setText("Primer Apellido");

        jLabel4.setText("Segundo Apellido");

        jLabel5.setText("Direccion");

        jLabel6.setText("Email");

        jLabel7.setText("Telefono");

        jLabel9.setText("Pais");

        jLabel10.setText("Identificacion");

        txt_nombre_hueped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_huepedActionPerformed(evt);
            }
        });

        cmb_pais_huesped.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mexico", "Argentina", "Canada", " " }));

        cmb_identificacion_huesped.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false", " " }));

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb_identificacion_huesped, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_pais_huesped, 0, 115, Short.MAX_VALUE)
                    .addComponent(txt_telefono_huesped)
                    .addComponent(txt_email_huesped)
                    .addComponent(txt_direccion_hueped)
                    .addComponent(txt_sa_huesped)
                    .addComponent(txt_pa_huesped)
                    .addComponent(txt_nombre_hueped))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nombre_hueped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pa_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_sa_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_direccion_hueped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_email_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_telefono_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmb_pais_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_identificacion_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombre_huepedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_huepedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_huepedActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        // TODO add your handling code here:
        Huesped h = new Huesped();
        HuespedDAO hdao = new HuespedDAO();
        h.setNombreHuesped(txt_nombre_hueped.getText());
        h.setPrimerApellido(txt_pa_huesped.getText());
        h.setSegundoApellido(txt_sa_huesped.getText());
        h.setDireccion(txt_direccion_hueped.getText());
        h.setEmail(txt_email_huesped.getText());
        h.setTelefono(txt_telefono_huesped.getText());
        h.setPais(String.valueOf(cmb_pais_huesped.getSelectedItem()));
        h.setIdentificacion(Boolean.valueOf(String.valueOf(cmb_identificacion_huesped.getSelectedItem())));
        System.out.println(conexion);
        if(hdao.agregarHuesped(conexion, h)){
            System.out.println("inserccion exitosa");
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    public void accionActualizarRegistro(Huesped h,conexionBD co){
        
        txt_nombre_hueped.setText(h.getNombreHuesped());
        txt_pa_huesped.setText(h.getPrimerApellido());
        txt_sa_huesped.setText(h.getSegundoApellido());
        txt_direccion_hueped.setText(h.getDireccion());
        txt_email_huesped.setText(h.getEmail());
        txt_telefono_huesped.setText(h.getTelefono());
        System.out.println("si accede al metodo accionActualizarRegistro linea 219");
        btn_actualizar.addActionListener(new ActionListener() {
            
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                Huesped h1 = new Huesped();
                HuespedDAO hdao = new HuespedDAO();
                h1.setIdHuesped(h.getIdHuesped());
                h1.setNombreHuesped(txt_nombre_hueped.getText());
                h1.setPrimerApellido(txt_pa_huesped.getText());
                h1.setSegundoApellido(txt_sa_huesped.getText());
                h1.setDireccion(txt_direccion_hueped.getText());
                h1.setEmail(txt_email_huesped.getText());
                h1.setTelefono(txt_telefono_huesped.getText());
                h1.setPais(String.valueOf(cmb_pais_huesped.getSelectedItem()));
                h1.setIdentificacion(Boolean.valueOf(String.valueOf(cmb_identificacion_huesped.getSelectedItem())));
                System.out.println(co);
                if(hdao.actualizarHuesped(co, h1)){
                    System.out.println("inserccion exitosa");
                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        btn_aceptar.setVisible(false);
        btn_actualizar.setBounds(170, 405, 115, 28);
        getContentPane().add(btn_actualizar);
        //btn_actualizar.addActionListener();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarHuesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JComboBox<String> cmb_identificacion_huesped;
    private javax.swing.JComboBox<String> cmb_pais_huesped;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_direccion_hueped;
    private javax.swing.JTextField txt_email_huesped;
    private javax.swing.JTextField txt_nombre_hueped;
    private javax.swing.JTextField txt_pa_huesped;
    private javax.swing.JTextField txt_sa_huesped;
    private javax.swing.JTextField txt_telefono_huesped;
    // End of variables declaration//GEN-END:variables
}
