/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import conexion.conexionBD;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.InvocationTargetException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author erik
 */
public class vistaPrincipal extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form vistaPrincipal
     */
    conexion.conexionBD con;
    VistaHuesped hp;
    vistaHabitacion vh;
    vistaPago vp;
    VistaHuespedReservacion vhr;
    
    
    public vistaPrincipal() {
        initComponents();
        setSize(900, 400);
        setLocationRelativeTo(null);
        btn_huesped.addActionListener(this);
        btn_habitacion.addActionListener(this);
        btn_pago.addActionListener(this);
        //panelGeneral.add(hp,java.awt.BorderLayout.CENTER);
    }
    
    public vistaPrincipal(conexionBD co, int tipo){
        con = co;
        initComponents();
        setSize(900, 400);
        setLocationRelativeTo(null);
        btn_huesped.addActionListener(this);
        btn_habitacion.addActionListener(this);
        btn_pago.addActionListener(this);
        btn_reservacion.addActionListener(this);
        
        if(tipo == 2){
            btn_habitacion.setVisible(false);
            btn_pago.setVisible(false);
            btn_huesped.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        btn_huesped = new javax.swing.JButton();
        btn_habitacion = new javax.swing.JButton();
        btn_pago = new javax.swing.JButton();
        btn_reservacion = new javax.swing.JButton();
        btn_graficas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGeneral.setLayout(new java.awt.BorderLayout());

        panelPrincipal.setLayout(new javax.swing.BoxLayout(panelPrincipal, javax.swing.BoxLayout.PAGE_AXIS));

        btn_huesped.setText("Huesped");
        panelPrincipal.add(btn_huesped);

        btn_habitacion.setText("Habitacion");
        panelPrincipal.add(btn_habitacion);

        btn_pago.setText("Pago");
        panelPrincipal.add(btn_pago);

        btn_reservacion.setText("Reservacion");
        panelPrincipal.add(btn_reservacion);

        btn_graficas.setText("Graficas");
        btn_graficas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_graficasActionPerformed(evt);
            }
        });
        panelPrincipal.add(btn_graficas);

        panelGeneral.add(panelPrincipal, java.awt.BorderLayout.LINE_START);

        getContentPane().add(panelGeneral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_graficasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_graficasActionPerformed
        // TODO add your handling code here:
        VistaGraficas vg = new VistaGraficas(con);
        vg.setVisible(true);
        panelGeneral.add(vg,java.awt.BorderLayout.CENTER);
        panelGeneral.validate();
        
    }//GEN-LAST:event_btn_graficasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_graficas;
    private javax.swing.JButton btn_habitacion;
    private javax.swing.JButton btn_huesped;
    private javax.swing.JButton btn_pago;
    private javax.swing.JButton btn_reservacion;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        if(ae.getActionCommand().equalsIgnoreCase("huesped")){
            
                System.out.println("funciona");
                
                java.awt.EventQueue.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        hp = new VistaHuesped(con);
                        hp.setVisible(true);
                        
                       /* if(vh.isVisible() || vp.isVisible() || vhr.isVisible()){
                    vh.setVisible(false);
                    vp.setVisible(false);
                    vhr.setVisible(false);
                }*/
                //hp.setVisible(true);
                panelGeneral.add(hp,java.awt.BorderLayout.CENTER);
                panelGeneral.validate();
                    }
                });
                if(vh.isVisible() || vp.isVisible() || vhr.isVisible()){
                    vh.setVisible(false);
                    vp.setVisible(false);
                    vhr.setVisible(false);
                }
                
                //hp = new VistaHuesped(con);
                //hp.setVisible(true);
                
                
                //hp = new VistaHuesped(con);
            
        }
        else if(ae.getActionCommand().equalsIgnoreCase("habitacion")){
            System.out.println("funciona 1");
            vh = new vistaHabitacion();
            
            vh.setVisible(true);
            panelGeneral.add(vh,java.awt.BorderLayout.CENTER);
            panelGeneral.validate();
            
            if(hp.isVisible() || vp.isVisible() || vhr.isVisible()){
                    hp.setVisible(false);
                    vp.setVisible(false);
                    vhr.setVisible(false);
                }
        }
        else if(ae.getActionCommand().equalsIgnoreCase("pago")){
            System.out.println("funciona 2");
            vp = new vistaPago();
            
            vp.setVisible(true);
            panelGeneral.add(vp,java.awt.BorderLayout.CENTER);
            panelGeneral.validate();
            if(hp.isVisible() || vh.isVisible() || vhr.isVisible()){
                hp.setVisible(false);
                vh.setVisible(false);
                vhr.setVisible(false);
            }
        }
        else if(ae.getActionCommand().equalsIgnoreCase("reservacion")){
            System.out.println("funciona 3");
            
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    vhr = new VistaHuespedReservacion(con);
                    vhr.setVisible(true);
                    panelGeneral.add(vhr,java.awt.BorderLayout.CENTER);
                    panelGeneral.validate();
                }
            });
            
            //vhr = new VistaHuespedReservacion(con);
            if(hp.isVisible() || vh.isVisible() || vp.isVisible()){
                hp.setVisible(false);
                vh.setVisible(false);
                vp.setVisible(false);
            }
            /*vhr.setVisible(true);
            panelGeneral.add(vhr,java.awt.BorderLayout.CENTER);
            panelGeneral.validate();*/
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
