/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import conexion.ReservacionDAO;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author erik
 */
public class VistaGraficas extends javax.swing.JPanel {

    conexion.conexionBD con;
    DefaultCategoryDataset datos = new DefaultCategoryDataset();
    JFreeChart Grafica;
    /**
     * Creates new form VistaGraficas
     */
    public VistaGraficas() {
        initComponents();
        
    }
    
    public VistaGraficas(conexion.conexionBD conexion) {
        initComponents();
        con = conexion;
        graficaMensual();
    }
    
    public void graficaMensual(){
        ReservacionDAO rdao = new ReservacionDAO();
        ArrayList meses = new ArrayList();
        ArrayList huespedes = new ArrayList();
        System.out.println("vista.VistaGraficas.graficaMensual()");
        rdao.datosGrafica(con, meses, huespedes);
        for (int i = 0; i < meses.size(); i++) {  
            datos.addValue(Integer.parseInt(meses.get(i).toString()), "meses", String.valueOf(huespedes.get(i)));
        }
        
        Grafica = ChartFactory.createBarChart3D("Meses", "Huespedes", "Cantidad", datos,PlotOrientation.HORIZONTAL,
                true, true, false);
        
        ChartPanel panel = new ChartPanel(Grafica);

        add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
