/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import conexion.HuespedDAO;
import conexion.conexionBD;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import modelo.TablaHuesped;
import modelo.Huesped;
/**
 *
 * @author erik
 */
public class VistaHuesped extends javax.swing.JPanel {
    
    conexionBD co;
    TablaHuesped tb = new TablaHuesped();
    HuespedDAO hdao = new HuespedDAO();
    String clave= "";
    
    /**
     * Creates new form Huesped
     */
    public VistaHuesped() {
        initComponents();
    }
    
    public VistaHuesped(conexion.conexionBD conexion) {
        initComponents();
        co = conexion;
        tb.ver_tabla(tbl_huesped, conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_busqueda_huesped = new javax.swing.JTextField();
        btn_buscar_huesped = new javax.swing.JButton();
        btn_agregar_huesped = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_huesped = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        txt_busqueda_huesped.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_busqueda_huespedKeyPressed(evt);
            }
        });

        btn_buscar_huesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/busqueda.png"))); // NOI18N
        btn_buscar_huesped.setText("Buscar");

        btn_agregar_huesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/agregar.png"))); // NOI18N
        btn_agregar_huesped.setText("Agregar");
        btn_agregar_huesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_huespedActionPerformed(evt);
            }
        });

        tbl_huesped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Primer Apellido", "Segundo Apellido", "Direccion", "Email", "Telefono", "Ciudad", "Pais", "Identificacion"
            }
        ));
        tbl_huesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_huespedMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_huesped);

        jPanel1.setBackground(new java.awt.Color(49, 128, 205));

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("Huesped");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_busqueda_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar_huesped)
                .addGap(18, 18, 18)
                .addComponent(btn_agregar_huesped)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_busqueda_huesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_huesped)
                    .addComponent(btn_agregar_huesped))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregar_huespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_huespedActionPerformed
        // TODO add your handling code here:
        AgregarHuesped ah = new AgregarHuesped(co,tbl_huesped);
        ah.setVisible(true);
        
    }//GEN-LAST:event_btn_agregar_huespedActionPerformed

    private void tbl_huespedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_huespedMouseClicked
        // TODO add your handling code here:
        
        int columna = tbl_huesped.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tbl_huesped.getRowHeight();
        
        if(row < tbl_huesped.getRowCount() && row >= 0 && columna < tbl_huesped.getColumnCount() && columna >= 0){
            Object value = tbl_huesped.getValueAt(row, columna);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton)value;
                if(boton.getName().equalsIgnoreCase("elm")){
                    int valor = Integer.parseInt(String.valueOf(tbl_huesped.getValueAt(row, 0)));
                    hdao.eliminarHuesped(co, valor);
                    tb.ver_tabla(tbl_huesped, co);
                }
                else if(boton.getName().equalsIgnoreCase("act")){
                    AgregarHuesped ah = new AgregarHuesped(co,tbl_huesped);
                    Huesped h = new Huesped();
                    h.setIdHuesped(Integer.parseInt(String.valueOf(tbl_huesped.getValueAt(row, 0))));
                    h.setNombreHuesped(String.valueOf(tbl_huesped.getValueAt(row, 1)));
                    h.setPrimerApellido(String.valueOf(tbl_huesped.getValueAt(row, 2)));
                    h.setSegundoApellido(String.valueOf(tbl_huesped.getValueAt(row, 3)));
                    h.setEmail(String.valueOf(tbl_huesped.getValueAt(row, 4)));
                    h.setTelefono(String.valueOf(tbl_huesped.getValueAt(row, 5)));
                    
                    ah.accionActualizarRegistro(h,co,tbl_huesped);
                    ah.setVisible(true);
                }
            }
        }
        
    }//GEN-LAST:event_tbl_huespedMouseClicked

    private void txt_busqueda_huespedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busqueda_huespedKeyPressed
        // TODO add your handling code here:
        
        clave += String.valueOf(evt.getKeyChar());
        if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE){
            
            String v = clave.substring(clave.length()-2, clave.length());
            clave = clave.replace(v, " ");
            clave = clave.strip();
            tb.actualizar_tabla(tbl_huesped, co,"nombre_huesped", clave);
        }
        else{
            tb.actualizar_tabla(tbl_huesped, co,"nombre_huesped", clave);
        }
        
    }//GEN-LAST:event_txt_busqueda_huespedKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_huesped;
    private javax.swing.JButton btn_buscar_huesped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_huesped;
    private javax.swing.JTextField txt_busqueda_huesped;
    // End of variables declaration//GEN-END:variables
}
