/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import conexion.ReservacionDAO;
import java.util.ArrayList;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author erik
 */
public class VistaGraficas extends javax.swing.JPanel {

    conexion.conexionBD con;
    DefaultCategoryDataset datos = new DefaultCategoryDataset();
    JFreeChart Grafica;
    /**
     * Creates new form VistaGraficas
     */
    public VistaGraficas() {
        initComponents();
        
    }
    
    public VistaGraficas(conexion.conexionBD conexion) {
        initComponents();
        con = conexion;
        graficaMensual();
    }
    
    public void graficaMensual(){
        ReservacionDAO rdao = new ReservacionDAO();
        ArrayList meses = new ArrayList();
        ArrayList huespedes = new ArrayList();
        rdao.datosGrafica(con, meses, huespedes);
        for (int i = 0; i < meses.size(); i++) {  
            //datos.addValue(Integer.parseInt(String.valueOf(huespedes.get(i))), mesInverso((int) meses.get(i)),"");
            datos.setValue((Number) huespedes.get(i),  mesInverso((int) meses.get(i)), "");
        }
        
        Grafica = ChartFactory.createBarChart3D("Hotel", "Cantidad", "Huespedes", datos,PlotOrientation.VERTICAL,
                true, true, false);
        
        ChartPanel panel = new ChartPanel(Grafica);
        JFrame Ventana = new JFrame("JFreeChart");
        Ventana.getContentPane().add(panel);
        Ventana.pack();
        Ventana.setVisible(true);
        Ventana.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
    
    public String mesInverso(int val){
        String mes = "";
        switch(val){
            case 1:
                mes = "Enero";
                break;
            case 2:
                mes = "Febrero";
                break;
            case 3:
                mes = "Marzo";
                break;
            case 4:
                mes = "Abril";
                break;
            case 5:
                mes = "Mayo";
                break;
            case 6:
                mes = "Junio";
                break;
            case 7:
                mes = "Julio";
                break;
            case 8:
                mes = "Agosto";
                break;
            case 9:
                mes = "Septiembre";
                break;
            case 10:
                mes = "Octubre";
                break;
            case 11:
                mes = "Noviembre";
                break;
            case 12:
                mes = "Diciembre";
                break;   
        }
        return mes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
